-- part 2 sql code
create schema fifa;

-- making sure that the encoding is appropriate if using a windows computer
set client_encoding to 'UTF8';

-- creating the table with all the column names
create table fifa.players_20 (
	sofifa_id text,
	player_url text,
	short_name text,
	long_name text,
	age numeric check(age >0),
	dob date,
	height_cm numeric check(age >0),
	weight_kg numeric check(age >0),
	nationality text,
	club text,
	overall numeric,
	potential numeric,
	value_eur numeric,
	wage_eur numeric,
	player_positions text,
	preferred_foot text,
	international_reputation numeric,
	weak_foot numeric,
	skill_moves numeric,
	work_rate text,
	body_type text,
	real_face text,
	release_clause_eur numeric,
	player_tags text,
	team_position text,
	team_jersey_number text,
	loaned_from text,
	joined date,
	contract_valid_until numeric,
	nation_position text,
	nation_jersey_number text,
	pace numeric,
	shooting numeric,
	passing numeric,
	dribbling numeric,
	defending numeric,
	physic numeric,
	gk_diving numeric,
	gk_handling numeric,
	gk_kicking numeric,
	gk_reflexes numeric,
	gk_speed numeric,
	gk_positioning numeric,
	player_traits text,
	attacking_crossing numeric,
	attacking_finishing numeric,
	attacking_heading_accuracy numeric,
	attacking_short_passing numeric,
	attacking_volleys numeric,
	skill_dribbling numeric,
	skill_curve numeric,
	skill_fk_accuracy numeric,
	skill_long_passing numeric,
	skill_ball_control numeric,
	movement_acceleration numeric,
	movement_sprint_speed numeric,
	movement_agility numeric,
	movement_reactions numeric,
	movement_balance numeric,
	power_shot_power numeric,
	power_jumping numeric,
	power_stamina numeric,
	power_strength numeric,
	power_long_shots numeric,
	mentality_aggression numeric,
	mentality_interceptions numeric,
	mentality_positioning numeric,
	mentality_vision numeric,
	mentality_penalties numeric,
	mentality_composure numeric,
	defending_marking numeric,
	defending_standing_tackle numeric,
	defending_sliding_tackle numeric,
	goalkeeping_diving numeric,
	goalkeeping_handling numeric,
	goalkeeping_kicking numeric,
	goalkeeping_positioning numeric,
	goalkeeping_reflexes numeric,
	ls text,
	st text,
	rs text,
	lw text,
	lf text,
	cf text,
	rf text,
	rw text,
	lam text,
	cam text,
	ram text,
	lm text,
	lcm text,
	cm text,
	rcm text,
	rm text,
	lwb text,
	ldm text,
	cdm text,
	rdm text,
	rwb text,
	lb text,
	lcb text,
	cb text,
	rcb text,
	rb text
);
 -- this is run in the sql shell
\copy fifa.players_20 from 'players_20.csv' with (format csv,header);

select * from fifa.players_20 limit 10;